### ISSUE TITLE
Questions about Xiaomi 8 compilation

### ISSUE THREAD

**Issue by Formula4j-plus** [palaych/mipa_kernel_xiaomi_sdm845#1]
Hello, thank you for your efforts.When I used your source code to compile the Xiaomi 8 kernel, I could not touch the wireguard file. Please tell me how to solve it.

**Comment by palaych** [comment]
Its should automatic fetch and clone when compiling kernel, kernel sources include script for this ( https://github.com/palaych/mipa_kernel_xiaomi_sdm845/commit/b50256a85f4e0f3cc42cae0905dd848e443765fb#diff-8a5ce03d5dc8c100d9d9ed18a2670b2b )
